apiVersion: v1
kind: Service
metadata:
  name: civility-backend-service
spec:
  selector:
    app: civility-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: civility-frontend-service
spec:
  selector:
    app: civility-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
